# Generated by Django 2.2.24 on 2021-09-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foldername', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(max_length=120, verbose_name='PALATA'),
        ),
    ]
